# Generated by Django 4.0 on 2022-01-30 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('co', '0002_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='caseassignment',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
